# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9646ee5e0670cc52835bf9f143aede825383457a812d96d82ee27fb812ddcd977975fd7d306be0069e05436bcc94f7758c69652a2226b9f0d1ecc2fa069816fc

test:
  secret_key_base: 4218d87bb7b00a4e8c86852f716a238a7fb13c28233e624cb082f80817685c491476d563827837606d06758929b917e2c0356de7dd41871cefada203cf9bef69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
